dt = {
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat",
    "":"preparing for dat"
}
data = [
    "one","1",
    "two","2",
    "three","3",
    "four","4",
    "five","5",
    "six","6",
    "seven","7",
    "eight","8",
    "nine","9",
    "ten","10",
    "eleven","11",
    "twelve","12",
    "thirtheen","13",
    "fourteen","14",
    "fifteen","15",
    "sixteen","16",
    "seventeen","17",
    "eighteen","18",
    "nineteen","19",
    "twenty","20",
    "thirty","30",
    "fourty","40",
    "fifty","50",
    "sixty","60",
    "seventy","70",
    "eighty","80",
    "ninty","90",
    "hundred","100",
    "thousand","1000",
    "tenthousand","10000",
    "lakhs","100000",
    "crore","10000000"
    
]
data1={"what is success":"success changes your envirnoment",
    "What is success":"success changes your envirnoment",
    "what is your name":"hello my name is deepu",
    "hi Deepu":"hello what is your name",
    "what are you doing":"Ippudey thinna",
    "name":"ratnadeep","age":"24",
    "love":"single",
    "i love you":"i love you too deepu",
    "I love you":"i love you too deepu",
    "tell me about yourself":"first of all thank you for giving me this opportunity to introduce myself my name is ratnadeep basically am from west godawari district jangaredygudem i did my graduation from vishnu institute of technology bhimavaram  i did my intermediate from srichaitanya vijayawada  i did my schooling from vidhya vikas jangareddygudem  i belong to a single parent family i my family there are three menbers me my brother and mother  my strengths are am honest am punchivate am hardworking  self motivated and quick learning my short term goal is to get good job in repuitated company it will improve my working skills and help me a lot in feature  my long term goal is to get more and more responsability and knowledge person and get become a good posoition in orginisition thats it and once again thankyou for giving me this great opportunity",
    "what are your career goals":"i want to create an app like instagram ",
    "climate":"hello macha how are you",
    "hi":"hello",
    "hai":"Hello",
    "hello":"hii how are you",
    "test":"preparing for dat",
    "why should I hire you":"preparing for dat",
    "what is your long-range objective":"preparing for dat",
    "what is your greatest accomplishment":"preparing for dat",
    "how has your education prepared you for your career":"preparing for dat",
    "are you a team player":"preparing for dat",
    "have you ever had a conflict with a boss or professor How did you resolve it":"preparing for dat",
    "what is your greatest strength":"preparing for dat",
    "what is your greatest weakness":"preparing for dat",
    "if I were to ask one of your professors (or a boss) to describe you, what would he or she say":"preparing for dat",
    "what qualities do you feel a successful manager should have":"preparing for dat",
    "if you had to live your life over again, what one thing would you change":"preparing for dat",
    "how would you describe your ideal job":"preparing for dat",
    "why did you choose this career":"preparing for dat",
    "when did you decide on this career":"preparing for dat",
    "what goals do you have in your career":"preparing for dat",
    "how do you plan to achieve your career goals":"preparing for dat",
    "how do you personally define success":"preparing for dat",
    "describe a situation in which you were successful":"preparing for dat",
    "what do you think it takes to be successful in this career":"preparing for dat",
    "what accomplishments have given you the most satisfaction in your life":"preparing for dat",
    "would you rather work with information or with people":"preparing for dat",
    "what motivates you":"I'm motivated by several things in my work. Doing meaningful work, recognition and having the tools to be successful are the most important motivators for me. For example, on one of my recent projects, we had the opportunity to develop leading edge systems for our company. It meant a lot to me to be selected to lead the team and we all worked well together, since we knew the importance of our work and the impact to our company. Our boss also knew that we needed additional tools to complete the project successfully. Those tools were provided and the project was delivered successfully. This project also led to recognition at both the team and department level. And that project was also noted as one of the reasons for my promotion to my current role…",
    "tell me about some of your recent goals and what you did to achieve them":"preparing for dat",
    "what are your short-term goals":"preparing for dat",
    "what are your mid-range goals":"preparing for dat",
    "what would your past manager say about you":"preparing for dat",
    "are you a goal-oriented person":"preparing for dat",
    "where do you want to be ten years from now":"preparing for dat",
    "do you handle conflict well":"preparing for dat",
    }

    